using Microsoft.EntityFrameworkCore;
using EmployeePromotionSystem.Data;
using EmployeePromotionSystem.Models;

namespace EmployeePromotionSystem.Services
{
    /// <summary>
    /// المحرك الذكي للحسابات - القلب النابض للنظام
    /// </summary>
    public class CalculationEngine : ICalculationEngine
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<CalculationEngine> _logger;

        public CalculationEngine(ApplicationDbContext context, ILogger<CalculationEngine> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// حساب وتطبيق جميع العلاوات والترفيعات المستحقة للموظف
        /// </summary>
        public async Task<List<PromotionHistory>> CalculateAndApplyEntitlementsAsync(Employee employee)
        {
            _logger.LogInformation($"بدء حساب الاستحقاقات للموظف: {employee.FullName}");

            var newEntitlements = new List<PromotionHistory>();
            var currentDate = DateTime.Now.Date;
            var lastEntitlementDate = employee.LastAllowanceDate.Date;

            // تحميل الأحداث المهنية للموظف
            var professionalEvents = await _context.ProfessionalEvents
                .Where(e => e.EmployeeId == employee.Id)
                .OrderBy(e => e.EventDate)
                .ToListAsync();

            // حلقة الحساب الرئيسية
            while (true)
            {
                // حساب تاريخ الاستحقاق التالي
                var nextEntitlementDate = CalculateNextEntitlementDate(lastEntitlementDate, professionalEvents);

                // إذا كان التاريخ في المستقبل، توقف
                if (nextEntitlementDate > currentDate)
                {
                    break;
                }

                // تحديد نوع الاستحقاق
                var entitlementType = GetNextEntitlementType(employee);
                var (newGrade, newStage) = CalculateNextGradeStage(employee);

                // إنشاء سجل الاستحقاق
                var promotionHistory = new PromotionHistory
                {
                    EmployeeId = employee.Id,
                    PromotionType = entitlementType,
                    EventDate = nextEntitlementDate,
                    PreviousGrade = employee.JobGrade,
                    PreviousStage = employee.JobStage,
                    NewGrade = newGrade,
                    NewStage = newStage,
                    PreviousTracker = employee.AllowanceTracker,
                    IsAutoGenerated = true,
                    CreatedAt = DateTime.Now
                };

                // تطبيق التغيير على الموظف
                ApplyEntitlementToEmployee(employee, entitlementType, newGrade, newStage);
                
                promotionHistory.NewTracker = employee.AllowanceTracker;
                promotionHistory.Description = promotionHistory.DetailedDescription;

                newEntitlements.Add(promotionHistory);
                lastEntitlementDate = nextEntitlementDate;

                _logger.LogInformation($"تم تطبيق {entitlementType} للموظف {employee.FullName} بتاريخ {nextEntitlementDate:yyyy-MM-dd}");
            }

            // حفظ السجلات الجديدة
            if (newEntitlements.Any())
            {
                await _context.PromotionHistories.AddRangeAsync(newEntitlements);
                
                // تحديث تاريخ آخر استحقاق للموظف
                employee.LastAllowanceDate = lastEntitlementDate;
                employee.UpdatedAt = DateTime.Now;
                
                await _context.SaveChangesAsync();
                
                _logger.LogInformation($"تم حفظ {newEntitlements.Count} استحقاق جديد للموظف {employee.FullName}");
            }

            return newEntitlements;
        }

        /// <summary>
        /// حساب تاريخ الاستحقاق القادم للموظف
        /// </summary>
        public async Task<DateTime> CalculateNextEntitlementDateAsync(Employee employee)
        {
            var professionalEvents = await _context.ProfessionalEvents
                .Where(e => e.EmployeeId == employee.Id)
                .OrderBy(e => e.EventDate)
                .ToListAsync();

            return CalculateNextEntitlementDate(employee.LastAllowanceDate, professionalEvents);
        }

        /// <summary>
        /// حساب تاريخ الاستحقاق التالي مع مراعاة الأحداث المهنية
        /// </summary>
        private DateTime CalculateNextEntitlementDate(DateTime baseDate, List<ProfessionalEvent> events)
        {
            // إضافة 12 شهراً كأساس
            var nextDate = baseDate.AddMonths(12);

            // حساب تأثير الأحداث المهنية
            var totalImpactMonths = CalculateEventsImpact(events, baseDate);

            // تطبيق التأثير
            nextDate = nextDate.AddMonths(totalImpactMonths);

            return nextDate;
        }

        /// <summary>
        /// حساب نوع الاستحقاق القادم (علاوة أم ترفيع)
        /// </summary>
        public PromotionType GetNextEntitlementType(Employee employee)
        {
            var parts = employee.AllowanceTracker.Split('/');
            if (parts.Length != 2) return PromotionType.Allowance;

            if (int.TryParse(parts[0], out int current) && int.TryParse(parts[1], out int total))
            {
                // إذا وصل إلى آخر مرحلة قبل الترفيع
                return current == total - 1 ? PromotionType.Promotion : PromotionType.Allowance;
            }

            return PromotionType.Allowance;
        }

        /// <summary>
        /// حساب الدرجة والمرحلة القادمة
        /// </summary>
        public (int grade, int stage) CalculateNextGradeStage(Employee employee)
        {
            var entitlementType = GetNextEntitlementType(employee);

            if (entitlementType == PromotionType.Allowance)
            {
                // علاوة: زيادة المرحلة
                return (employee.JobGrade, employee.JobStage + 1);
            }
            else
            {
                // ترفيع: تقليل الدرجة وإعادة المرحلة إلى 1
                var newGrade = Math.Max(1, employee.JobGrade - 1);
                return (newGrade, 1);
            }
        }

        /// <summary>
        /// حساب تأثير الأحداث المهنية على مدة الاستحقاق
        /// </summary>
        public int CalculateEventsImpact(IEnumerable<ProfessionalEvent> events, DateTime baseDate)
        {
            var totalImpact = 0;

            foreach (var eventItem in events.Where(e => e.EventDate >= baseDate))
            {
                totalImpact += eventItem.GetImpactInMonths();
            }

            return totalImpact;
        }

        /// <summary>
        /// تطبيق الاستحقاق على بيانات الموظف
        /// </summary>
        private void ApplyEntitlementToEmployee(Employee employee, PromotionType type, int newGrade, int newStage)
        {
            employee.JobGrade = newGrade;
            employee.JobStage = newStage;

            // تحديث مؤشر التتبع
            var parts = employee.AllowanceTracker.Split('/');
            if (parts.Length == 2 && int.TryParse(parts[0], out int current) && int.TryParse(parts[1], out int total))
            {
                if (type == PromotionType.Promotion)
                {
                    // إعادة تصفير المؤشر بعد الترفيع
                    var newTotal = GetTrackerTotalForGrade(newGrade);
                    employee.AllowanceTracker = $"0/{newTotal}";
                }
                else
                {
                    // زيادة العداد للعلاوة
                    employee.AllowanceTracker = $"{current + 1}/{total}";
                }
            }
        }

        /// <summary>
        /// الحصول على إجمالي مؤشر التتبع حسب الدرجة
        /// </summary>
        private int GetTrackerTotalForGrade(int grade)
        {
            return grade switch
            {
                >= 6 and <= 10 => 4, // الدرجات 10-6: 3 علاوات + 1 ترفيع = 4
                >= 2 and <= 5 => 5,  // الدرجات 5-2: 4 علاوات + 1 ترفيع = 5
                1 => 11,              // الدرجة الأولى: 10 علاوات كحد أقصى
                _ => 4
            };
        }

        /// <summary>
        /// التحقق من صحة مؤشر التتبع
        /// </summary>
        public bool ValidateTracker(string tracker, int grade)
        {
            var parts = tracker.Split('/');
            if (parts.Length != 2) return false;

            if (!int.TryParse(parts[0], out int current) || !int.TryParse(parts[1], out int total))
                return false;

            var expectedTotal = GetTrackerTotalForGrade(grade);
            return total == expectedTotal && current >= 0 && current < total;
        }

        /// <summary>
        /// إعادة حساب كامل للموظف من نقطة البداية
        /// </summary>
        public async Task<List<PromotionHistory>> RecalculateFromStartAsync(Employee employee)
        {
            _logger.LogInformation($"بدء إعادة الحساب الكامل للموظف: {employee.FullName}");

            // حذف السجلات المولدة تلقائياً
            var existingRecords = await _context.PromotionHistories
                .Where(h => h.EmployeeId == employee.Id && h.IsAutoGenerated)
                .ToListAsync();

            _context.PromotionHistories.RemoveRange(existingRecords);

            // إعادة تعيين بيانات الموظف إلى نقطة البداية
            // (يجب أن تكون هذه البيانات محفوظة في مكان آمن أو يمكن استنتاجها)
            
            // إعادة حساب جميع الاستحقاقات
            var newEntitlements = await CalculateAndApplyEntitlementsAsync(employee);

            _logger.LogInformation($"تم إعادة حساب {newEntitlements.Count} استحقاق للموظف {employee.FullName}");

            return newEntitlements;
        }

        /// <summary>
        /// معالجة الحالات الخاصة مثل الترفيع السريع
        /// </summary>
        private bool IsEligibleForFastPromotion(Employee employee)
        {
            // قاعدة الترفيع السريع: موظف جديد بدبلوم على الدرجة 8/5
            return employee.StartDate.Date == employee.LastAllowanceDate.Date &&
                   employee.AcademicDegree.Contains("دبلوم") &&
                   employee.JobGrade == 8 &&
                   employee.JobStage == 5;
        }
    }
}

