using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeePromotionSystem.Models
{
    /// <summary>
    /// نموذج تاريخ العلاوات والترفيعات
    /// </summary>
    public class PromotionHistory
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "نوع الحدث مطلوب")]
        public PromotionType PromotionType { get; set; }

        [Required(ErrorMessage = "تاريخ الحدث مطلوب")]
        public DateTime EventDate { get; set; }

        // الدرجة والمرحلة قبل الحدث
        public int PreviousGrade { get; set; }
        public int PreviousStage { get; set; }

        // الدرجة والمرحلة بعد الحدث
        public int NewGrade { get; set; }
        public int NewStage { get; set; }

        [StringLength(500)]
        public string? Description { get; set; }

        // مؤشر التتبع قبل وبعد الحدث
        [StringLength(10)]
        public string? PreviousTracker { get; set; }
        [StringLength(10)]
        public string? NewTracker { get; set; }

        public bool IsAutoGenerated { get; set; } = true; // تم إنشاؤه تلقائياً بواسطة المحرك الحسابي

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // العلاقات
        [ForeignKey("EmployeeId")]
        public virtual Employee Employee { get; set; } = null!;

        /// <summary>
        /// وصف مفصل للحدث
        /// </summary>
        public string DetailedDescription
        {
            get
            {
                return PromotionType switch
                {
                    PromotionType.Allowance => $"علاوة سنوية: انتقل من الدرجة {PreviousGrade} المرحلة {PreviousStage} إلى الدرجة {NewGrade} المرحلة {NewStage}",
                    PromotionType.Promotion => $"ترفيع: انتقل من الدرجة {PreviousGrade} المرحلة {PreviousStage} إلى الدرجة {NewGrade} المرحلة {NewStage}",
                    _ => Description ?? "حدث غير محدد"
                };
            }
        }

        /// <summary>
        /// أيقونة الحدث
        /// </summary>
        public string EventIcon
        {
            get
            {
                return PromotionType switch
                {
                    PromotionType.Allowance => "💰",
                    PromotionType.Promotion => "⬆️",
                    _ => "📋"
                };
            }
        }

        /// <summary>
        /// لون الحدث
        /// </summary>
        public string EventColor
        {
            get
            {
                return PromotionType switch
                {
                    PromotionType.Allowance => "#4CAF50", // أخضر
                    PromotionType.Promotion => "#2196F3", // أزرق
                    _ => "#9E9E9E" // رمادي
                };
            }
        }
    }

    /// <summary>
    /// أنواع الترفيعات والعلاوات
    /// </summary>
    public enum PromotionType
    {
        [Display(Name = "علاوة سنوية")]
        Allowance = 1,

        [Display(Name = "ترفيع")]
        Promotion = 2
    }
}

